import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white min-h-screen flex flex-col font-sans">
        {/* Navigation Bar */}
        <nav className="w-full px-6 py-4 flex justify-between items-center border-b border-white/10 bg-black/80 sticky top-0 z-50">
          <div className="text-2xl font-bold tracking-widest uppercase">
            Slanted Culture
          </div>
          <ul className="flex gap-6 text-lg font-medium">
            <li><a href="/" className="hover:text-accent transition">Home</a></li>
            <li><a href="/shop" className="hover:text-accent transition">Shop/Gallery</a></li>
            <li><a href="/about" className="hover:text-accent transition">About</a></li>
            <li><a href="/events" className="hover:text-accent transition">Events/Blog</a></li>
            <li><a href="/faq" className="hover:text-accent transition">FAQ</a></li>
            <li><a href="/contact" className="hover:text-accent transition">Contact</a></li>
          </ul>
        </nav>
        {/* Main Content */}
        <main className="flex-1 w-full max-w-5xl mx-auto px-4 py-8">
          {children}
        </main>
        {/* Footer */}
        <footer className="w-full px-6 py-8 border-t border-white/10 bg-black/90 text-center text-sm flex flex-col gap-2 items-center">
          <div className="flex gap-4 justify-center mb-2">
            <a href="#" className="hover:text-accent">Instagram</a>
            <a href="#" className="hover:text-accent">YouTube</a>
            <a href="#" className="hover:text-accent">TikTok</a>
            <a href="#" className="hover:text-accent">Threads</a>
          </div>
          <div> {new Date().getFullYear()} Slanted Culture. All rights reserved.</div>
        </footer>
      </body>
    </html>
  );
}
